// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package hero.login.rmi;

public final class YOYOLoginRMIImpl_Stub
    extends java.rmi.server.RemoteStub
    implements hero.login.rmi.IYOYOLoginRMI
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_GMReplyLetter_0;
    private static java.lang.reflect.Method $method_addGoodsForPlayer_1;
    private static java.lang.reflect.Method $method_addPointForPlayer_2;
    private static java.lang.reflect.Method $method_blink_3;
    private static java.lang.reflect.Method $method_checkStatusOfRun_4;
    private static java.lang.reflect.Method $method_createRole_5;
    private static java.lang.reflect.Method $method_createSessionID_6;
    private static java.lang.reflect.Method $method_deleteRole_7;
    private static java.lang.reflect.Method $method_getGameMapList_8;
    private static java.lang.reflect.Method $method_getGoodsName_9;
    private static java.lang.reflect.Method $method_getOnlinePlayerNumber_10;
    private static java.lang.reflect.Method $method_getPlayerInfoByNickname_11;
    private static java.lang.reflect.Method $method_getPlayerInfoByUserID_12;
    private static java.lang.reflect.Method $method_listDefaultRole_13;
    private static java.lang.reflect.Method $method_listRole_14;
    private static java.lang.reflect.Method $method_modifyPlayerInfo_15;
    private static java.lang.reflect.Method $method_resetPlayers_16;
    private static java.lang.reflect.Method $method_resetPlayersStatus_17;
    private static java.lang.reflect.Method $method_sendNoticeGM_18;
    private static java.lang.reflect.Method $method_smsCallBack_19;
    private static java.lang.reflect.Method $method_szfFeeCallBack_20;
    private static java.lang.reflect.Method $method_updateServerExpMoudlus_21;
    
    static {
	try {
	    $method_GMReplyLetter_0 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("GMReplyLetter", new java.lang.Class[] {int.class});
	    $method_addGoodsForPlayer_1 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("addGoodsForPlayer", new java.lang.Class[] {int.class, int.class, int.class});
	    $method_addPointForPlayer_2 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("addPointForPlayer", new java.lang.Class[] {int.class, int.class});
	    $method_blink_3 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("blink", new java.lang.Class[] {short.class, int.class});
	    $method_checkStatusOfRun_4 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("checkStatusOfRun", new java.lang.Class[] {});
	    $method_createRole_5 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("createRole", new java.lang.Class[] {int.class, short.class, int.class, java.lang.String[].class});
	    $method_createSessionID_6 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("createSessionID", new java.lang.Class[] {int.class, int.class});
	    $method_deleteRole_7 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("deleteRole", new java.lang.Class[] {int.class});
	    $method_getGameMapList_8 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("getGameMapList", new java.lang.Class[] {});
	    $method_getGoodsName_9 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("getGoodsName", new java.lang.Class[] {int.class});
	    $method_getOnlinePlayerNumber_10 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("getOnlinePlayerNumber", new java.lang.Class[] {});
	    $method_getPlayerInfoByNickname_11 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("getPlayerInfoByNickname", new java.lang.Class[] {java.lang.String.class});
	    $method_getPlayerInfoByUserID_12 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("getPlayerInfoByUserID", new java.lang.Class[] {int.class});
	    $method_listDefaultRole_13 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("listDefaultRole", new java.lang.Class[] {});
	    $method_listRole_14 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("listRole", new java.lang.Class[] {int[].class});
	    $method_modifyPlayerInfo_15 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("modifyPlayerInfo", new java.lang.Class[] {int.class, int.class, int.class, int.class, int.class});
	    $method_resetPlayers_16 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("resetPlayers", new java.lang.Class[] {});
	    $method_resetPlayersStatus_17 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("resetPlayersStatus", new java.lang.Class[] {int.class});
	    $method_sendNoticeGM_18 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("sendNoticeGM", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	    $method_smsCallBack_19 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("smsCallBack", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	    $method_szfFeeCallBack_20 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("szfFeeCallBack", new java.lang.Class[] {int.class, java.lang.String.class, byte.class, java.lang.String.class, int.class});
	    $method_updateServerExpMoudlus_21 = hero.login.rmi.IYOYOLoginRMI.class.getMethod("updateServerExpMoudlus", new java.lang.Class[] {float.class, java.lang.String.class, java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public YOYOLoginRMIImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of GMReplyLetter(int)
    public void GMReplyLetter(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_GMReplyLetter_0, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 3362286105506325484L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of addGoodsForPlayer(int, int, int)
    public int addGoodsForPlayer(int $param_int_1, int $param_int_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_addGoodsForPlayer_1, new java.lang.Object[] {new java.lang.Integer($param_int_1), new java.lang.Integer($param_int_2), new java.lang.Integer($param_int_3)}, -2125371492887870376L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of addPointForPlayer(int, int)
    public int addPointForPlayer(int $param_int_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_addPointForPlayer_2, new java.lang.Object[] {new java.lang.Integer($param_int_1), new java.lang.Integer($param_int_2)}, 4134609681590273210L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of blink(short, int)
    public int blink(short $param_short_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_blink_3, new java.lang.Object[] {new java.lang.Short($param_short_1), new java.lang.Integer($param_int_2)}, 6344898611983036648L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of checkStatusOfRun()
    public boolean checkStatusOfRun()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_checkStatusOfRun_4, null, -819198521117889461L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of createRole(int, short, int, String[])
    public byte[] createRole(int $param_int_1, short $param_short_2, int $param_int_3, java.lang.String[] $param_arrayOf_String_4)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_createRole_5, new java.lang.Object[] {new java.lang.Integer($param_int_1), new java.lang.Short($param_short_2), new java.lang.Integer($param_int_3), $param_arrayOf_String_4}, 7821257337317999579L);
	    return ((byte[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of createSessionID(int, int)
    public int createSessionID(int $param_int_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_createSessionID_6, new java.lang.Object[] {new java.lang.Integer($param_int_1), new java.lang.Integer($param_int_2)}, -5866673518348984378L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of deleteRole(int)
    public int deleteRole(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_deleteRole_7, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 5582361264620256667L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getGameMapList()
    public java.lang.String getGameMapList()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getGameMapList_8, null, 722486599017532250L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getGoodsName(int)
    public java.lang.String getGoodsName(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getGoodsName_9, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 6483968136812330620L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getOnlinePlayerNumber()
    public int getOnlinePlayerNumber()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getOnlinePlayerNumber_10, null, 7993396340870161215L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getPlayerInfoByNickname(String)
    public java.lang.String getPlayerInfoByNickname(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getPlayerInfoByNickname_11, new java.lang.Object[] {$param_String_1}, -3178326323566395682L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getPlayerInfoByUserID(int)
    public java.lang.String getPlayerInfoByUserID(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getPlayerInfoByUserID_12, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 3986221029998072520L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of listDefaultRole()
    public byte[] listDefaultRole()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_listDefaultRole_13, null, 4314811098416132512L);
	    return ((byte[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of listRole(int[])
    public byte[] listRole(int[] $param_arrayOf_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_listRole_14, new java.lang.Object[] {$param_arrayOf_int_1}, 5271732377633397755L);
	    return ((byte[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of modifyPlayerInfo(int, int, int, int, int)
    public int modifyPlayerInfo(int $param_int_1, int $param_int_2, int $param_int_3, int $param_int_4, int $param_int_5)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_modifyPlayerInfo_15, new java.lang.Object[] {new java.lang.Integer($param_int_1), new java.lang.Integer($param_int_2), new java.lang.Integer($param_int_3), new java.lang.Integer($param_int_4), new java.lang.Integer($param_int_5)}, -5065521471865725353L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of resetPlayers()
    public void resetPlayers()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_resetPlayers_16, null, 2615789245185974199L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of resetPlayersStatus(int)
    public boolean resetPlayersStatus(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_resetPlayersStatus_17, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 1329813045848175969L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of sendNoticeGM(String, String)
    public void sendNoticeGM(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_sendNoticeGM_18, new java.lang.Object[] {$param_String_1, $param_String_2}, 3199868298211475341L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of smsCallBack(String, String)
    public void smsCallBack(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_smsCallBack_19, new java.lang.Object[] {$param_String_1, $param_String_2}, -4697181263741900115L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of szfFeeCallBack(int, String, byte, String, int)
    public int szfFeeCallBack(int $param_int_1, java.lang.String $param_String_2, byte $param_byte_3, java.lang.String $param_String_4, int $param_int_5)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_szfFeeCallBack_20, new java.lang.Object[] {new java.lang.Integer($param_int_1), $param_String_2, new java.lang.Byte($param_byte_3), $param_String_4, new java.lang.Integer($param_int_5)}, 2978294565660189059L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of updateServerExpMoudlus(float, String, String)
    public boolean updateServerExpMoudlus(float $param_float_1, java.lang.String $param_String_2, java.lang.String $param_String_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_updateServerExpMoudlus_21, new java.lang.Object[] {new java.lang.Float($param_float_1), $param_String_2, $param_String_3}, -4561818133829480338L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
